; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Libre2Excel"
#define MyAppVersion "1.5"
#define MyAppPublisher "RLS Technologies"
#define MyAppURL "https://rlstechnologies.com"
#define MyAppExeName "librecsv2excel.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{32DA8A49-605C-4201-A808-FAC9E4C5676C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=librecsv2excel_setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "F:\Python\LibreViewExcel\dist\librecsv2excel.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\Python\LibreViewExcel\dist\Libre2excel.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\Python\LibreViewExcel\dist\glucose_chart.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "F:\Python\LibreViewExcel\dist\glucose_report.xlsm"; DestDir: "{code:GetLocalDocumentsFolder}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commondesktop}\Glucose_report Excel - Shortcut"; Filename: "{code:GetLocalDocumentsFolder}\glucose_report.xlsm"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function GetLocalDocumentsFolder(Param: string): string;
begin
  Result := GetEnv('USERPROFILE') + '\Documents';
end;



